# -*- coding: utf-8 -*-
"""WISE Cube Case Competition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDZeszoji_KJcmAdbAEMCmTcO4d1X1uK
"""

import pandas as pd
import seaborn as sns
import numpy as np
import folium
from folium import plugins
import geopandas as gpd
import matplotlib.pyplot as plt

!pip install geopandas

data_url = 'https://raw.githubusercontent.com/aryabari/leishmaniasis_trial_dataset/main/leishmaniasis_hiv_trial_data_1000_cases.csv'
data = pd.read_csv(data_url)

from IPython.display import display
display(data)

# mapping data with a chloroplete (heat) map

map_df = data

world_map = folium.Map(max_bounds= True, min_zoom= 3)
world_cities = map_df[['latitude', 'longitude']].values
plugins.HeatMap(world_cities, radius=16).add_to(world_map)
folium.LayerControl().add_to(world_map)



world_map